name: Publish Log4brains
on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false # required by JamesIves/github-pages-deploy-action
          fetch-depth: 0 # required by Log4brains to work correctly (needs the whole Git history)
      
      - uses: actions/setup-node@v4
        with:
          node-version: '22.15.0' # Match project requirement
      
      - uses: pnpm/action-setup@v4
        with:
          version: 10.11.0 # Match project requirement
      
      - name: Install dependencies and build Log4brains
        run: |
          pnpm install
          pnpm log4brains build --basePath /${{ github.event.repository.name }}/log4brains
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: .log4brains/out
          target-folder: log4brains
          clean: true